server:
  port: 8092
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/rs-ecommerce
    username: root
    password: root
    tomcat.max-wait: 20000
    tomcat.max-active: 50
    tomcat.max-idle: 20
    tomcat.min-idle: 15
    validationQuery: SELECT 1
    jpa:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL8Dialect
      hibernate:
        ddl-auto: update
        
management:
  server:
    port: 8093
  endpoints:
    web:
      exposure:
        include: "*" # This will expose all end-points through Spring Actuator
  endpoint:
    health:
      show-details: "always"
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
